"""create travel_records

Revision ID: 07d7b726ccbf
Revises: 90c1c1484669
Create Date: 2025-09-02 23:35:50.438051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07d7b726ccbf'
down_revision: Union[str, Sequence[str], None] = '90c1c1484669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travel_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('destination_type', sa.Enum('CITY', 'NATURE', 'BEACH', 'MUSEUM', 'PARK', 'MOUNTAIN', 'DESERT', 'HISTORICAL', 'FOOD', 'OTHER', name='destination_type'), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('visited_at', sa.DateTime(), nullable=False),
    sa.Column('place_external_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_travel_records_rating_1_5'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travel_records_id'), 'travel_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_travel_records_id'), table_name='travel_records')
    op.drop_table('travel_records')
    # ### end Alembic commands ###
