"""add photo fields to travel_records

Revision ID: cc7d6deacb38
Revises: 07d7b726ccbf
Create Date: 2025-09-03 03:44:40.048833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc7d6deacb38'
down_revision: Union[str, Sequence[str], None] = '07d7b726ccbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travel_records', sa.Column('photo_path', sa.String(length=512), nullable=True))
    op.add_column('travel_records', sa.Column('photo_content_type', sa.String(length=64), nullable=True))
    op.add_column('travel_records', sa.Column('photo_size_bytes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('travel_records', 'photo_size_bytes')
    op.drop_column('travel_records', 'photo_content_type')
    op.drop_column('travel_records', 'photo_path')
    # ### end Alembic commands ###
